/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Meta
         * @description Filter values for the topbar — read directly from the ETL output.
         */
        get: operations["get_meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Kpis */
        get: operations["get_kpis_api_kpis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Forecast */
        get: operations["get_forecast_api_forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forecast/quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forecast Quality */
        get: operations["forecast_quality_api_forecast_quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Gap */
        get: operations["get_gap_api_gap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Drivers */
        get: operations["get_drivers_api_drivers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Simulate */
        post: operations["post_simulate_api_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/promos/roi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Promo Roi */
        get: operations["get_promo_roi_api_promos_roi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Recommend */
        post: operations["post_recommend_api_recommend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Mock streaming response. Real impl runs the smolagents CodeAgent on `fast` profile.
         */
        post: operations["chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/explain-view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Explain View */
        post: operations["post_explain_view_api_explain_view_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/parquet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Parquet Files
         * @description List local snapshot Parquet files available for diagnostics.
         */
        get: operations["list_parquet_files_api_debug_parquet_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/parquet/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview Parquet
         * @description Preview an allowlisted local snapshot Parquet file.
         */
        get: operations["preview_parquet_api_debug_parquet__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/anomalies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Anomalies */
        get: operations["get_anomalies_api_anomalies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forecast/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Forecast Timeline
         * @description Monthly aggregated forecast + target, one row per month.
         */
        get: operations["forecast_timeline_api_forecast_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forecast/by-sub-channel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Forecast By Sub Channel
         * @description Per-sub_channel rollup, optionally scoped to a single period.
         */
        get: operations["forecast_by_sub_channel_api_forecast_by_sub_channel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forecast/by-brand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Forecast By Brand
         * @description Per-brand rollup, period-scoped. Sorted by absolute forecast volume.
         */
        get: operations["forecast_by_brand_api_forecast_by_brand_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pulse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pulse
         * @description One-call headline for the UK home page.
         *
         *     Answers the brief's literal question — "is this month going to close above
         *     or below the estimated budget" — at the portfolio level (all SKUs, all
         *     sub-channels). Returns the worst-contributing brand and sub-channel so the
         *     home page can call out where to look first.
         */
        get: operations["pulse_api_pulse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get News */
        get: operations["get_news_api_news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/refresh-news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh News
         * @description Re-run Tavily, merge into the cache, purge >30-day rows.
         *
         *     Hackathon-grade endpoint: no auth. Don't link from the UI. Call from
         *     a script or `make news`.
         */
        post: operations["refresh_news_api_admin_refresh_news_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/brief": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Brief */
        post: operations["post_brief_api_brief_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/external-signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * External Signals
         * @description Per-SKU × sub_channel external context for a target period.
         *
         *     Returns a compact bundle the Decision page can render in a sidebar:
         *       - weather: avg temperature + anomaly vs climatology
         *       - search: Estrella/lager/beer interest (0-100 Google Trends)
         *       - retail: ONS retail + food/drink index
         *       - events: UK holidays + sport in that month
         *       - source: "actuals" or "prior_year" (so the UI can disclose proxy use)
         */
        get: operations["external_signals_api_external_signals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pricing/gross-per-hl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gross Per Hl */
        get: operations["gross_per_hl_api_pricing_gross_per_hl_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnomalyEvent */
        AnomalyEvent: {
            /** Sku */
            sku: string;
            /** Sub Channel */
            sub_channel: string;
            /** Period */
            period: string;
            /** Actual Hl */
            actual_hl: number;
            /** Expected Hl */
            expected_hl: number;
            /** Z Score */
            z_score: number;
            /** Candidate Cause */
            candidate_cause: string;
        };
        /** BrandRollup */
        BrandRollup: {
            /** Brand */
            brand: string;
            /** Forecast */
            forecast: number;
            /** Target */
            target: number;
            /** Gap Pct */
            gap_pct: number;
            /** Gap Hl */
            gap_hl: number;
            /** Gap Gbp */
            gap_gbp?: number | null;
            /** N Skus */
            n_skus: number;
        };
        /** BriefAgendaItem */
        BriefAgendaItem: {
            /** Time */
            time: string;
            /** Title */
            title: string;
        };
        /** BriefNewsItem */
        BriefNewsItem: {
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Source Domain */
            source_domain: string;
            /** Published At */
            published_at: string | null;
        };
        /** BriefRequest */
        BriefRequest: {
            /** Customer */
            customer: string;
            /**
             * Customer Key
             * @enum {string}
             */
            customer_key: "tesco" | "sainsburys" | "asda" | "morrisons" | "on_trade";
            /** Meeting Weekday */
            meeting_weekday: string;
            /** Meeting In Days */
            meeting_in_days: number;
            /** Skus */
            skus: components["schemas"]["BriefSkuInput"][];
        };
        /** BriefResponse */
        BriefResponse: {
            /** Customer */
            customer: string;
            /** Meeting Label */
            meeting_label: string;
            /** Headline */
            headline: string;
            /** Push Forward Title */
            push_forward_title: string;
            /** Push Forward Body */
            push_forward_body: string;
            /** Top Skus */
            top_skus: components["schemas"]["BriefSkuRow"][];
            /** Market Context */
            market_context: components["schemas"]["BriefNewsItem"][];
            /** Agenda */
            agenda: components["schemas"]["BriefAgendaItem"][];
        };
        /**
         * BriefSkuInput
         * @description One at-risk SKU passed in by the frontend.
         */
        BriefSkuInput: {
            /** Sku */
            sku: string;
            /** Sub Channel */
            sub_channel: string;
            /** Period */
            period: string;
            /** Sku Label */
            sku_label: string;
            /** Gap Pct */
            gap_pct: number;
            /** Gap Hl */
            gap_hl: number;
            /** Top Driver */
            top_driver?: string | null;
        };
        /** BriefSkuRow */
        BriefSkuRow: {
            /** Sku Label */
            sku_label: string;
            /** Sub Channel */
            sub_channel: string;
            /** Period */
            period: string;
            /** Gap Pct */
            gap_pct: number;
            /** Gap Hl */
            gap_hl: number;
            /** Top Driver */
            top_driver: string | null;
            /** Recommended Ask */
            recommended_ask: string | null;
        };
        /**
         * CalendarEvent
         * @description A calendar event (bank holiday, sport final, etc.) relevant for beer demand.
         *
         *     Rendered as a dashed vertical line with a label on the forecast chart.
         */
        CalendarEvent: {
            /** Period */
            period: string;
            /** Label */
            label: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "holiday" | "sport" | "weather";
        };
        /** ChatMessage */
        ChatMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "system" | "user" | "assistant" | "tool";
            /** Content */
            content: string;
            /** Tool Calls */
            tool_calls?: {
                [key: string]: unknown;
            }[];
        };
        /** ChatRequest */
        ChatRequest: {
            /** Session Id */
            session_id?: string | null;
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
        };
        /** Driver */
        Driver: {
            /** Feature */
            feature: string;
            /** Shap Value */
            shap_value: number;
            /**
             * Direction
             * @enum {string}
             */
            direction: "positive" | "negative";
            /** Explanation */
            explanation: string;
        };
        /** ExplainViewRequest */
        ExplainViewRequest: {
            /**
             * Page
             * @enum {string}
             */
            page: "overview" | "forecast" | "drivers" | "promos" | "simulator" | "recommendations" | "chat";
            /** Filters */
            filters: {
                [key: string]: unknown;
            };
            /** Visible State */
            visible_state: {
                [key: string]: unknown;
            };
        };
        /** ExplainViewSummary */
        ExplainViewSummary: {
            /** Headline */
            headline: string;
            /** Bullets */
            bullets: string[];
            /** Suggested Next Action */
            suggested_next_action?: string | null;
        };
        /** ExternalSignals */
        ExternalSignals: {
            /** Period */
            period: string;
            /** Period Start */
            period_start: string;
            /**
             * Source
             * @enum {string}
             */
            source: "actuals" | "prior_year";
            /** Source Period */
            source_period: string;
            weather: components["schemas"]["WeatherSignal"];
            search: components["schemas"]["SearchSignal"];
            retail: components["schemas"]["RetailSignal"];
            /** Events */
            events: components["schemas"]["CalendarEvent"][];
        };
        /** ForecastPoint */
        ForecastPoint: {
            /** Period */
            period: string;
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /** Point */
            point: number;
            /** Lo80 */
            lo80: number;
            /** Hi80 */
            hi80: number;
            /** Lo95 */
            lo95: number;
            /** Hi95 */
            hi95: number;
            /**
             * Is Actual
             * @default false
             */
            is_actual: boolean;
        };
        /** ForecastSeries */
        ForecastSeries: {
            /** Sku */
            sku: string;
            /** Sub Channel */
            sub_channel: string;
            /**
             * Granularity
             * @default month
             * @enum {string}
             */
            granularity: "month" | "week";
            /** Points */
            points?: components["schemas"]["ForecastPoint"][];
            /** Promo Windows */
            promo_windows?: components["schemas"]["PromoWindow"][];
            /** Events */
            events?: components["schemas"]["CalendarEvent"][];
        };
        /** GapItem */
        GapItem: {
            /** Sku */
            sku: string;
            /** Sub Channel */
            sub_channel: string;
            /** Period */
            period: string;
            /** Forecast Hl */
            forecast_hl: number;
            /** Budget Hl */
            budget_hl: number;
            /** Gap Hl */
            gap_hl: number;
            /** Gap Pct */
            gap_pct: number;
            /**
             * Confidence
             * @default medium
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
            /**
             * History Hl
             * @default []
             */
            history_hl: number[];
            /** Prev Week Gap Pct */
            prev_week_gap_pct?: number | null;
            /** Gap Gbp */
            gap_gbp?: number | null;
        };
        /**
         * GrossPriceRate
         * @description Approximated "normal" price per hectolitre for a data slice.
         *
         *     Computed as Σ revenue / Σ Hl over the requested filter. The underlying
         *     source is net sales rather than true gross sales — at the aggregate
         *     level (many promo + non-promo months) it averages out to a reasonable
         *     proxy for the unit value. See backend/app/services/pricing.py.
         */
        GrossPriceRate: {
            /** Gbp Per Hl */
            gbp_per_hl: number | null;
            /** N Rows */
            n_rows: number;
            /** Note */
            note: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KpiSummary */
        KpiSummary: {
            /** Total Forecast Hl */
            total_forecast_hl: number;
            /** Total Budget Hl */
            total_budget_hl: number;
            /** Gap Hl */
            gap_hl: number;
            /** Gap Pct */
            gap_pct: number;
            /** On Track Skus */
            on_track_skus: number;
            /** Off Track Skus */
            off_track_skus: number;
            /** Period Range */
            period_range: [
                string,
                string
            ];
        };
        /** MetaResponse */
        MetaResponse: {
            /** Brands */
            brands: string[];
            /** Skus */
            skus: {
                [key: string]: unknown;
            }[];
            /** Sub Channels */
            sub_channels: string[];
            /** Sub Channels Labeled */
            sub_channels_labeled?: {
                [key: string]: unknown;
            }[];
            /** Sales Channels */
            sales_channels: string[];
            /** Sales Channels Labeled */
            sales_channels_labeled?: {
                [key: string]: unknown;
            }[];
            /** Period Range */
            period_range: [
                string,
                string
            ];
            /** Hero */
            hero: {
                [key: string]: unknown;
            };
        };
        /**
         * NewsArticle
         * @description A single trade-press article surfaced by Tavily, tagged for context.
         */
        NewsArticle: {
            /**
             * Id
             * @description SHA1 of the article URL — used as the dedup key.
             */
            id: string;
            /** Url */
            url: string;
            /** Title */
            title: string;
            /**
             * Summary
             * @description Tavily's snippet, ~200 chars.
             */
            summary: string;
            /** Source Domain */
            source_domain: string;
            /**
             * Published At
             * @description When Tavily reported the article was published. May be null.
             */
            published_at?: string | null;
            /**
             * Fetched At
             * Format: date-time
             * @description When we last refreshed this row.
             */
            fetched_at: string;
            /** Brand Tags */
            brand_tags?: string[];
            /** Channel Tags */
            channel_tags?: string[];
            /** Event Tags */
            event_tags?: string[];
            /**
             * Relevance Score
             * @description Tavily's 0..1 relevance score from the original query.
             * @default 0
             */
            relevance_score: number;
        };
        /**
         * NewsResponse
         * @description What GET /api/news returns.
         */
        NewsResponse: {
            /** Articles */
            articles: components["schemas"]["NewsArticle"][];
            /**
             * Updated At
             * @description Latest refresh timestamp; null if cache is empty.
             */
            updated_at?: string | null;
        };
        /** PromoROI */
        PromoROI: {
            /** Promo Type */
            promo_type: string;
            /** Sub Channel */
            sub_channel: string;
            /** Avg Lift Pct */
            avg_lift_pct: number;
            /** Avg Lift Hl */
            avg_lift_hl: number;
            /** Estimated Cost */
            estimated_cost?: number | null;
            /** Roi */
            roi?: number | null;
            /** N Observations */
            n_observations: number;
            /**
             * Confidence
             * @default low
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
            /**
             * Lift History
             * @default []
             */
            lift_history: number[];
        };
        /**
         * PromoWindow
         * @description A past or upcoming promo period for this SKU × sub_channel.
         *
         *     Used by the forecast chart to render shaded vertical bands so the user
         *     can see *why* a past month over/underperformed, or what's coming up.
         */
        PromoWindow: {
            /** Period Start */
            period_start: string;
            /** Period End */
            period_end: string;
            /** Label */
            label: string;
            /**
             * Type
             * @enum {string}
             */
            type: "price" | "multibuy" | "display";
        };
        /**
         * Pulse
         * @description Headline answer to the brief's "will this month close above/below
         *     budget?" question. Single period, aggregated across all SKUs and channels.
         */
        Pulse: {
            /** Period */
            period: string;
            /** Period Start */
            period_start: string;
            /** Total Forecast Hl */
            total_forecast_hl: number;
            /** Total Target Hl */
            total_target_hl: number;
            /** Gap Hl */
            gap_hl: number;
            /** Gap Pct */
            gap_pct: number;
            /** Gap Gbp */
            gap_gbp?: number | null;
            /** Gbp Per Hl */
            gbp_per_hl?: number | null;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
            /** N Skus At Risk */
            n_skus_at_risk: number;
            worst_brand?: components["schemas"]["WorstSlice"] | null;
            worst_channel?: components["schemas"]["WorstSlice"] | null;
        };
        /** QualityPoint */
        QualityPoint: {
            /** Period */
            period: string;
            /** Predicted Hl */
            predicted_hl: number;
            /** Actual Hl */
            actual_hl: number;
            /** Error Pct */
            error_pct: number;
        };
        /** QualityResponse */
        QualityResponse: {
            /** Points */
            points?: components["schemas"]["QualityPoint"][];
            /**
             * Mape Pct
             * @default 0
             */
            mape_pct: number;
            /**
             * Mape Recent Pct
             * @default 0
             */
            mape_recent_pct: number;
            /**
             * N Points
             * @default 0
             */
            n_points: number;
        };
        /** RecommendRequest */
        RecommendRequest: {
            /** Sku */
            sku: string;
            /** Sub Channel */
            sub_channel: string;
            /** Period */
            period: string;
        };
        /** RecommendationAction */
        RecommendationAction: {
            /** Action */
            action: string;
            /** Target Sku */
            target_sku: string;
            /** Target Sub Channel */
            target_sub_channel: string;
            /** Target Months */
            target_months: string[];
            /** Expected Lift Hl */
            expected_lift_hl: number;
            /** Expected Gap Closed Pct */
            expected_gap_closed_pct: number;
            /** Estimated Cost */
            estimated_cost?: number | null;
            /**
             * Confidence
             * @default medium
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
            /** Evidence */
            evidence?: string[];
        };
        /** RecommendationResponse */
        RecommendationResponse: {
            /** Sku */
            sku: string;
            /** Sub Channel */
            sub_channel: string;
            /** Period */
            period: string;
            /** Current Gap Hl */
            current_gap_hl: number;
            /** Current Gap Pct */
            current_gap_pct: number;
            /** Scenarios */
            scenarios: components["schemas"]["RecommendationScenario"][];
        };
        /** RecommendationScenario */
        RecommendationScenario: {
            /**
             * Label
             * @enum {string}
             */
            label: "conservative" | "balanced" | "aggressive";
            /** Headline */
            headline: string;
            /** Actions */
            actions?: components["schemas"]["RecommendationAction"][];
            /** Total Expected Gap Closed Pct */
            total_expected_gap_closed_pct: number;
            /** Risk Notes */
            risk_notes: string;
        };
        /**
         * RefreshResult
         * @description What POST /api/admin/refresh-news returns.
         */
        RefreshResult: {
            /**
             * Fetched
             * @description Total articles returned by Tavily across all queries.
             */
            fetched: number;
            /**
             * New Articles
             * @description Articles that weren't already in the cache.
             */
            new_articles: number;
            /**
             * Cache Size
             * @description Cache size after the refresh + purge.
             */
            cache_size: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Error
             * @description Non-null when the refresh ran into a recoverable error (e.g. missing key, Tavily 5xx). The cache is preserved in those cases.
             */
            error?: string | null;
        };
        /** RetailSignal */
        RetailSignal: {
            /** Retail Index */
            retail_index?: number | null;
            /** Food Drink Index */
            food_drink_index?: number | null;
            /** Food Drink Trend */
            food_drink_trend?: ("up" | "flat" | "down") | null;
        };
        /** SearchSignal */
        SearchSignal: {
            /** Estrella */
            estrella?: number | null;
            /** Lager */
            lager?: number | null;
            /** Beer */
            beer?: number | null;
            /** Estrella Trend */
            estrella_trend?: ("up" | "flat" | "down") | null;
        };
        /** SimulationRequest */
        SimulationRequest: {
            /** Sku */
            sku: string;
            /** Sub Channel */
            sub_channel: string;
            /** Months */
            months: string[];
            /** Discount Pct */
            discount_pct: number;
            /**
             * Promo Type
             * @default multi-buy
             * @enum {string}
             */
            promo_type: "multi-buy" | "price-cut" | "rollback" | "clearance" | "listing";
        };
        /** SimulationResult */
        SimulationResult: {
            baseline: components["schemas"]["ForecastSeries"];
            simulated: components["schemas"]["ForecastSeries"];
            /** Gap Before Hl */
            gap_before_hl: number;
            /** Gap After Hl */
            gap_after_hl: number;
            /** Gap Closed Pct */
            gap_closed_pct: number;
            /** Estimated Cost */
            estimated_cost?: number | null;
            /** Notes */
            notes: string;
        };
        /** SubChannelRollup */
        SubChannelRollup: {
            /** Name */
            name: string;
            /** Code */
            code: string;
            /** Forecast */
            forecast: number;
            /** Target */
            target: number;
            /** Gap Pct */
            gap_pct: number;
            /** Gap Hl */
            gap_hl: number;
            /** Gap Gbp */
            gap_gbp?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeatherSignal */
        WeatherSignal: {
            /** Temp C */
            temp_c?: number | null;
            /** Anomaly C */
            anomaly_c?: number | null;
        };
        /**
         * WorstSlice
         * @description Used for both `worst_brand` and `worst_channel` in the pulse response.
         */
        WorstSlice: {
            /** Name */
            name: string;
            /** Gap Hl */
            gap_hl: number;
            /** Gap Pct */
            gap_pct: number;
            /** Gap Gbp */
            gap_gbp?: number | null;
            /** Code */
            code?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
    get_kpis_api_kpis_get: {
        parameters: {
            query?: {
                brand?: string | null;
                sub_channel?: string | null;
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_forecast_api_forecast_get: {
        parameters: {
            query: {
                sku: string;
                sub_channel: string;
                granularity?: string;
                horizon?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastSeries"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forecast_quality_api_forecast_quality_get: {
        parameters: {
            query: {
                sku: string;
                /** @description sub_channel — kept short for URL clarity */
                channel: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_gap_api_gap_get: {
        parameters: {
            query?: {
                brand?: string | null;
                sub_channel?: string | null;
                from?: string | null;
                to?: string | null;
                sort?: string;
                limit?: number;
                min_quality?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GapItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_drivers_api_drivers_get: {
        parameters: {
            query: {
                sku: string;
                sub_channel: string;
                period?: string;
                top_k?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Driver"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_simulate_api_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_promo_roi_api_promos_roi_get: {
        parameters: {
            query?: {
                sub_channel?: string | null;
                top_k?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromoROI"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_recommend_api_recommend_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_explain_view_api_explain_view_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplainViewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainViewSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_parquet_files_api_debug_parquet_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    preview_parquet_api_debug_parquet__name__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                search?: string | null;
                column?: string | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_anomalies_api_anomalies_get: {
        parameters: {
            query?: {
                sku?: string | null;
                brand?: string | null;
                sub_channel?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnomalyEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forecast_timeline_api_forecast_timeline_get: {
        parameters: {
            query?: {
                brand?: string | null;
                sub_channel?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forecast_by_sub_channel_api_forecast_by_sub_channel_get: {
        parameters: {
            query?: {
                brand?: string | null;
                /** @description "May.26" or "2026-05" */
                period?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubChannelRollup"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forecast_by_brand_api_forecast_by_brand_get: {
        parameters: {
            query?: {
                sub_channel?: string | null;
                /** @description "May.26" or "2026-05" */
                period?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandRollup"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pulse_api_pulse_get: {
        parameters: {
            query?: {
                /** @description "May.26" or "2026-05" — defaults to the earliest forecast month */
                period?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pulse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_news_api_news_get: {
        parameters: {
            query?: {
                /** @description Brand tag, e.g. 'estrella' */
                brand?: string | null;
                /** @description Channel tag, e.g. 'tesco' */
                channel?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_news_api_admin_refresh_news_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResult"];
                };
            };
        };
    };
    post_brief_api_brief_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BriefRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    external_signals_api_external_signals_get: {
        parameters: {
            query: {
                sku: string;
                sub_channel: string;
                /** @description "Nov.26" or "2026-11" */
                period?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalSignals"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gross_per_hl_api_pricing_gross_per_hl_get: {
        parameters: {
            query?: {
                sku?: string | null;
                brand?: string | null;
                sub_channel?: string | null;
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrossPriceRate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
