/**
 * Recommendations — 3 scenario cards (conservative / balanced / aggressive).
 */

import { useSearchParams, useNavigate } from "react-router-dom"
import { Skeleton } from "@/components/ui/skeleton"
import { StickyFilterBar } from "@/components/StickyFilterBar"
import { useRecommend, useMeta } from "@/lib/hooks"
import { formatHl, formatPercent, formatGBP } from "@/lib/format"
import { PageHeader, Card, CardTitle } from "./Overview"

export default function Recommendations() {
  const [params] = useSearchParams()
  const navigate = useNavigate()
  const sku = params.get("sku")
  const sub_channel = params.get("sub_channel") ?? "GROCERY"
  const period = params.get("period") ?? "Nov.26"
  const { data: meta } = useMeta()
  const { data: rec, isLoading } = useRecommend(sku, sub_channel, period)

  const skuLabel = meta?.skus.find(s => s.id === sku)?.label ?? sku ?? "—"
  const channelLabel = meta?.sub_channels_labeled.find(c => c.code === sub_channel)?.label ?? sub_channel

  return (
    <div className="px-6 pt-5 pb-12 max-w-7xl mx-auto">
      <PageHeader title="Recommended actions" subtitle="Three scenarios generated by the LLM from real forecast + driver + promo-ROI data." />
      <StickyFilterBar />

      {!sku && (
        <Card className="mt-4">
          <div className="py-12 px-6 text-center text-sm text-muted-foreground">
            Pick a SKU above. We'll generate three commercial scenarios to close its gap.
          </div>
        </Card>
      )}

      {sku && (
        <Card className="mt-4">
          <div className="px-4 py-3 text-sm flex items-center justify-between flex-wrap gap-2">
            <div>
              <span className="font-medium">{skuLabel}</span>
              <span className="text-muted-foreground"> · {channelLabel} · </span>
              <span className="font-medium">{period}</span>
            </div>
            {rec && (
              <div className="text-xs text-muted-foreground">
                Current gap:&nbsp;
                <span className="font-semibold" style={{ color: rec.current_gap_pct < 0 ? "var(--negative)" : "var(--positive)" }}>
                  {formatPercent(rec.current_gap_pct)}
                </span>
                &nbsp;({formatHl(rec.current_gap_hl)})
              </div>
            )}
          </div>
        </Card>
      )}

      {isLoading && (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 mt-4">
          {[0, 1, 2].map(i => <Skeleton key={i} className="h-[420px] rounded-lg" />)}
        </div>
      )}

      {rec && (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 mt-4">
          {rec.scenarios.map(s => {
            const isBalanced = s.label === "balanced"
            return (
              <Card key={s.label} className={isBalanced ? "ring-2 ring-primary/40" : ""}>
                <div className="px-4 pt-3.5 pb-3 border-b border-border">
                  <div className="flex items-center justify-between">
                    <div className="text-[13.5px] font-medium tracking-tight capitalize">{s.label}</div>
                    {isBalanced && (
                      <span className="inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-medium bg-primary text-primary-foreground">
                        Recommended
                      </span>
                    )}
                  </div>
                  <div className="text-[11px] text-muted-foreground mt-1">{s.headline}</div>
                </div>

                <div className="px-4 py-4 space-y-4">
                  <div>
                    <div className="text-[11px] uppercase tracking-wide text-muted-foreground font-medium">Total gap closure</div>
                    <div className="text-2xl font-semibold tabular-nums tracking-tight mt-1" style={{
                      color: s.total_expected_gap_closed_pct > 0 ? "var(--positive)" : "var(--neutral)",
                    }}>
                      {formatPercent(s.total_expected_gap_closed_pct)}
                    </div>
                  </div>

                  <div className="space-y-2">
                    <div className="text-[11px] uppercase tracking-wide text-muted-foreground font-medium">Actions</div>
                    {s.actions.map((a, i) => (
                      <div key={i} className="border border-border rounded-md p-3 text-sm space-y-1.5">
                        <div className="font-medium">{a.action}</div>
                        <div className="text-[11px] text-muted-foreground flex flex-wrap gap-x-3 gap-y-1">
                          <span>Lift: {formatHl(a.expected_lift_hl)}</span>
                          <span>Closes: {formatPercent(a.expected_gap_closed_pct)}</span>
                          {a.estimated_cost && <span>Cost: {formatGBP(a.estimated_cost)}</span>}
                          <span className="inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-medium border border-border text-muted-foreground">
                            {a.confidence}
                          </span>
                        </div>
                        {a.evidence?.length > 0 && (
                          <ul className="text-[11px] text-muted-foreground/80 space-y-0.5 pt-1.5">
                            {a.evidence.map((e, j) => (
                              <li key={j} className="flex gap-1.5"><span className="text-muted-foreground/40">•</span>{e}</li>
                            ))}
                          </ul>
                        )}
                      </div>
                    ))}
                  </div>

                  <div className="text-[11px] text-muted-foreground border-t border-border pt-3">
                    <span className="font-medium text-foreground">Risk: </span>{s.risk_notes}
                  </div>

                  <button
                    onClick={() => navigate(`/simulator?sku=${sku}&sub_channel=${encodeURIComponent(sub_channel)}`)}
                    className={`w-full h-8 rounded-md text-xs font-medium transition ${
                      isBalanced
                        ? "bg-primary text-primary-foreground hover:bg-primary/90"
                        : "border border-border text-foreground hover:bg-accent/60"
                    }`}
                  >
                    Tweak in simulator →
                  </button>
                </div>
              </Card>
            )
          })}
        </div>
      )}
    </div>
  )
}
