/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Meta
         * @description Filter values for the topbar. Real impl reads from snapshots/meta.json.
         */
        get: operations["get_meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Kpis */
        get: operations["get_kpis_api_kpis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Forecast
         * @description Mock forecast. Real impl reads from snapshots/forecast.parquet.
         */
        get: operations["get_forecast_api_forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Gap
         * @description Mock gap rows. Real impl joins forecast vs budget snapshots.
         */
        get: operations["get_gap_api_gap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Drivers
         * @description Mock SHAP drivers. Real impl runs TreeExplainer on the p50 LightGBM.
         */
        get: operations["get_drivers_api_drivers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate
         * @description Mock simulator. Real impl re-runs the LightGBM ensemble with modified exogenous frame.
         */
        post: operations["simulate_api_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/promos/roi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Promo Roi
         * @description Mock ROI ranking. Real impl reads snapshots/promo_roi.parquet (CausalImpact).
         */
        get: operations["get_promo_roi_api_promos_roi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recommend
         * @description Mock 3-scenario response. Real impl uses Kimi-K2-Instruct via Instructor on the `deep` profile.
         */
        post: operations["recommend_api_recommend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Mock streaming response. Real impl runs the smolagents CodeAgent on `fast` profile.
         */
        post: operations["chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/explain-view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Explain View
         * @description Mock summary. Real impl uses Llama-3.3 via Groq on the `fast` profile.
         */
        post: operations["explain_view_api_explain_view_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChatMessage */
        ChatMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "system" | "user" | "assistant" | "tool";
            /** Content */
            content: string;
            /** Tool Calls */
            tool_calls?: {
                [key: string]: unknown;
            }[];
        };
        /** ChatRequest */
        ChatRequest: {
            /** Session Id */
            session_id?: string | null;
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
        };
        /** Driver */
        Driver: {
            /** Feature */
            feature: string;
            /** Shap Value */
            shap_value: number;
            /**
             * Direction
             * @enum {string}
             */
            direction: "positive" | "negative";
            /** Explanation */
            explanation: string;
        };
        /** ExplainViewRequest */
        ExplainViewRequest: {
            /**
             * Page
             * @enum {string}
             */
            page: "overview" | "forecast" | "drivers" | "promos" | "simulator" | "recommendations" | "chat";
            /** Filters */
            filters: {
                [key: string]: unknown;
            };
            /** Visible State */
            visible_state: {
                [key: string]: unknown;
            };
        };
        /** ExplainViewSummary */
        ExplainViewSummary: {
            /** Headline */
            headline: string;
            /** Bullets */
            bullets: string[];
            /** Suggested Next Action */
            suggested_next_action?: string | null;
        };
        /** ForecastPoint */
        ForecastPoint: {
            /** Period */
            period: string;
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /** Point */
            point: number;
            /** Lo80 */
            lo80: number;
            /** Hi80 */
            hi80: number;
            /** Lo95 */
            lo95: number;
            /** Hi95 */
            hi95: number;
            /**
             * Is Actual
             * @default false
             */
            is_actual: boolean;
        };
        /** ForecastSeries */
        ForecastSeries: {
            /** Sku */
            sku: string;
            /** Sub Channel */
            sub_channel: string;
            /**
             * Granularity
             * @default month
             * @enum {string}
             */
            granularity: "month" | "week";
            /** Points */
            points?: components["schemas"]["ForecastPoint"][];
        };
        /** GapItem */
        GapItem: {
            /** Sku */
            sku: string;
            /** Sub Channel */
            sub_channel: string;
            /** Period */
            period: string;
            /** Forecast Hl */
            forecast_hl: number;
            /** Budget Hl */
            budget_hl: number;
            /** Gap Hl */
            gap_hl: number;
            /** Gap Pct */
            gap_pct: number;
            /**
             * Confidence
             * @default medium
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KpiSummary */
        KpiSummary: {
            /** Total Forecast Hl */
            total_forecast_hl: number;
            /** Total Budget Hl */
            total_budget_hl: number;
            /** Gap Hl */
            gap_hl: number;
            /** Gap Pct */
            gap_pct: number;
            /** On Track Skus */
            on_track_skus: number;
            /** Off Track Skus */
            off_track_skus: number;
            /** Period Range */
            period_range: [
                string,
                string
            ];
        };
        /** MetaResponse */
        MetaResponse: {
            /** Brands */
            brands: string[];
            /** Skus */
            skus: {
                [key: string]: unknown;
            }[];
            /** Sub Channels */
            sub_channels: string[];
            /** Sales Channels */
            sales_channels: string[];
            /** Period Range */
            period_range: [
                string,
                string
            ];
            /** Hero */
            hero: {
                [key: string]: unknown;
            };
        };
        /** PromoROI */
        PromoROI: {
            /** Promo Type */
            promo_type: string;
            /** Sub Channel */
            sub_channel: string;
            /** Avg Lift Pct */
            avg_lift_pct: number;
            /** Avg Lift Hl */
            avg_lift_hl: number;
            /** Estimated Cost */
            estimated_cost?: number | null;
            /** Roi */
            roi?: number | null;
            /** N Observations */
            n_observations: number;
            /**
             * Confidence
             * @default low
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
        };
        /** RecommendRequest */
        RecommendRequest: {
            /** Sku */
            sku: string;
            /** Sub Channel */
            sub_channel: string;
            /** Period */
            period: string;
        };
        /** RecommendationAction */
        RecommendationAction: {
            /** Action */
            action: string;
            /** Target Sku */
            target_sku: string;
            /** Target Sub Channel */
            target_sub_channel: string;
            /** Target Months */
            target_months: string[];
            /** Expected Lift Hl */
            expected_lift_hl: number;
            /** Expected Gap Closed Pct */
            expected_gap_closed_pct: number;
            /** Estimated Cost */
            estimated_cost?: number | null;
            /**
             * Confidence
             * @default medium
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
            /** Evidence */
            evidence?: string[];
        };
        /** RecommendationResponse */
        RecommendationResponse: {
            /** Sku */
            sku: string;
            /** Sub Channel */
            sub_channel: string;
            /** Period */
            period: string;
            /** Current Gap Hl */
            current_gap_hl: number;
            /** Current Gap Pct */
            current_gap_pct: number;
            /** Scenarios */
            scenarios: components["schemas"]["RecommendationScenario"][];
        };
        /** RecommendationScenario */
        RecommendationScenario: {
            /**
             * Label
             * @enum {string}
             */
            label: "conservative" | "balanced" | "aggressive";
            /** Headline */
            headline: string;
            /** Actions */
            actions?: components["schemas"]["RecommendationAction"][];
            /** Total Expected Gap Closed Pct */
            total_expected_gap_closed_pct: number;
            /** Risk Notes */
            risk_notes: string;
        };
        /** SimulationRequest */
        SimulationRequest: {
            /** Sku */
            sku: string;
            /** Sub Channel */
            sub_channel: string;
            /** Months */
            months: string[];
            /** Discount Pct */
            discount_pct: number;
            /**
             * Promo Type
             * @default multi-pack
             * @enum {string}
             */
            promo_type: "multi-pack" | "price-cut" | "feature" | "display" | "off-invoice" | "other";
        };
        /** SimulationResult */
        SimulationResult: {
            baseline: components["schemas"]["ForecastSeries"];
            simulated: components["schemas"]["ForecastSeries"];
            /** Gap Before Hl */
            gap_before_hl: number;
            /** Gap After Hl */
            gap_after_hl: number;
            /** Gap Closed Pct */
            gap_closed_pct: number;
            /** Estimated Cost */
            estimated_cost?: number | null;
            /** Notes */
            notes: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
    get_kpis_api_kpis_get: {
        parameters: {
            query?: {
                brand?: string | null;
                sub_channel?: string | null;
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_forecast_api_forecast_get: {
        parameters: {
            query: {
                sku: string;
                sub_channel: string;
                granularity?: string;
                horizon?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastSeries"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_gap_api_gap_get: {
        parameters: {
            query?: {
                brand?: string | null;
                sub_channel?: string | null;
                from?: string | null;
                to?: string | null;
                sort?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GapItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_drivers_api_drivers_get: {
        parameters: {
            query: {
                sku: string;
                sub_channel: string;
                period: string;
                top_k?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Driver"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_api_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_promo_roi_api_promos_roi_get: {
        parameters: {
            query?: {
                sub_channel?: string | null;
                top_k?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromoROI"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommend_api_recommend_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_view_api_explain_view_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplainViewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainViewSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
